/* DashView service worker — makes the app work offline.
   Bump VERSION on release; the file list below is generated by the build step. */
var VERSION = 'dv-2026.09.5';
var PRECACHE = [
 "index.html",
 "dashboard.html",
 "people.html",
 "ai.html",
 "share.html",
 "settings.html",
 "data-studio.html",
 "404.html",
 "manifest.json",
 "css/ai-embed.css",
 "css/base.css",
 "css/index-pro.css",
 "css/components.css",
 "css/dashboard-hr-match.css",
 "css/dashboard-pro.css",
 "css/dashboard.css",
 "css/dashview-suite.css",
 "css/merged.css",
 "css/odoo-live.css",
 "css/odoo-pro.css",
 "css/people.css",
 "css/people-pro.css",
 "css/pro-upgrade.css",
 "css/security.css",
 "css/studio-dash.css",
 "js/ai-api-config.js",
 "js/ai-embed.js",
 "js/ai-odoo-agent.js",
 "js/ai-engine.js",
 "js/app.js",
 "js/audit-live.js",
 "js/auth-service.js",
 "js/config.js",
 "js/dashboard-pro.js",
 "js/dashview-api.js",
 "js/dv-security.js",
 "js/hr-app.js",
 "js/hr-icons.js",
 "js/hr-store.js",
 "js/hr-views.js",
 "js/odoo-client.js",
 "js/odoo-connectivity.js",
 "js/odoo-live.js",
 "js/odoo-profiles.js",
 "js/odoo-service.js",
 "js/overview-live.js",
 "js/people-shell.js",
 "js/report-engine.js",
 "js/security-ui.js",
 "js/shell.js",
 "js/studio-core.js",
 "js/studio-ui.js",
 "js/tasks.js",
 "js/widget-builder.js",
 "assets/favicon.svg",
 "assets/favicon-32x32.png",
 "assets/apple-touch-icon.png",
 "assets/icon-192.png",
 "assets/icon-512.png",
 "assets/icon-maskable-192.png",
 "assets/icon-maskable-512.png"
];
var CDN = /^https:\/\/(cdn\.jsdelivr\.net|cdnjs\.cloudflare\.com|fonts\.googleapis\.com|fonts\.gstatic\.com)\//;

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(VERSION).then(function (c) {
    return Promise.all(PRECACHE.map(function (u) { return c.add(u).catch(function () {}); }));
  }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (ks) {
    return Promise.all(ks.filter(function (k) { return k !== VERSION; }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener('message', function (e) { if (e.data === 'skip') self.skipWaiting(); });

function keep(req, res) {
  if (!res || !(res.ok || res.type === 'opaque')) return;
  var copy = res.clone();
  caches.open(VERSION).then(function (c) { c.put(req, copy); });
}

self.addEventListener('fetch', function (e) {
  var r = e.request, u = new URL(r.url);
  if (r.method !== 'GET') return;
  if (u.origin !== location.origin && !CDN.test(r.url)) return; /* Odoo, GitHub and AI calls always go to the network */
  if (u.pathname.indexOf('/api/') !== -1) return;

  if (r.mode === 'navigate') { /* pages: fresh when online, cached when not */
    e.respondWith(fetch(r).then(function (res) { keep(r, res); return res; }).catch(function () {
      return caches.match(r, { ignoreSearch: true }).then(function (m) { return m || caches.match('dashboard.html'); });
    }));
    return;
  }
  e.respondWith(caches.match(r).then(function (hit) { /* assets: instant from cache, refreshed in background */
    var net = fetch(r).then(function (res) { keep(r, res); return res; }).catch(function () { return hit; });
    return hit || net;
  }));
});
